version: "3.9"
services:
  spring-app-image:
    image: spring-app-image
    container_name: spring-app-container
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - spring-network
    depends_on:
      - mysql
  mysql:
    image: mysql
    container_name: zdxTnTA4k1cmjZPJ9ibl
    environment:
      - MYSQL_ADDON_DB="byqjxwxazigzfoob7oob"
      - MYSQL_ADDON_PASSWORD="zdxTnTA4k1cmjZPJ9ibl"
      - MYSQL_ROOT_PASSWORD="zdxTnTA4k1cmjZPJ9ibl"
      - MYSQL_ADDON_USER="uugpjo5tf2yghh1f"
    ports:
      - "3307:3306"
    networks:
      spring-network:
    volumes:
      - mysql-volume:/var/lib/mysql
networks:
  spring-network:
volumes:
  mysql-volume: