FROM maven:4.0.0-openjdk-17-slim AS build
COPY . .
RUN mvn clean package -DskipTests


FROM openjdk:17-jdk-slim
COPY --from=build /target/taller-0.0.1-SNAPSHOT.jar taller-0.0.1-SNAPSHOT.jar
EXPOSE 8080

ENTRYPOINT [ "java", "-jar", "taller-0.0.1-SNAPSHOT.jar"]